// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleAlcoholSensor.EF;

#nullable disable

namespace VehicleAlcoholSensor.EF.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230321200010_migr_0000_2023")]
    partial class migr_0000_2023
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Base.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Device", "public");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Base.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Concentration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VehicleDriverDeviceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleDriverDeviceId");

                    b.ToTable("Metrics", "public");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Base.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles", "public");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.MultiDimension.VehicleDriverDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleDriverDevices", "public");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EMail")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Base.Metric", b =>
                {
                    b.HasOne("VehicleAlcoholSensor.Domain.Entities.MultiDimension.VehicleDriverDevice", "VehicleDriverDevice")
                        .WithMany("Metrics")
                        .HasForeignKey("VehicleDriverDeviceId");

                    b.Navigation("VehicleDriverDevice");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.MultiDimension.VehicleDriverDevice", b =>
                {
                    b.HasOne("VehicleAlcoholSensor.Domain.Entities.Base.Device", "Device")
                        .WithMany("VehicleDriverDevices")
                        .HasForeignKey("DeviceId");

                    b.HasOne("VehicleAlcoholSensor.Domain.Entities.Security.User", "Driver")
                        .WithMany("VehicleDriverDevices")
                        .HasForeignKey("DriverId");

                    b.HasOne("VehicleAlcoholSensor.Domain.Entities.Base.Vehicle", "Vehicle")
                        .WithMany("VehicleDriverDevices")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Device");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Base.Device", b =>
                {
                    b.Navigation("VehicleDriverDevices");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Base.Vehicle", b =>
                {
                    b.Navigation("VehicleDriverDevices");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.MultiDimension.VehicleDriverDevice", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("VehicleAlcoholSensor.Domain.Entities.Security.User", b =>
                {
                    b.Navigation("VehicleDriverDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
